//
//  DesignStudioStyles.swift
//  DesignStudioExpress
//
//  Created by Kate on 11/12/15.
//  Copyright (c) 2015 AlexanderInteractive. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class DesignStudioStyles : NSObject {

    //// Cache

    private struct Cache {
        static let secondaryOrange: UIColor = UIColor(red: 0.984, green: 0.612, blue: 0.573, alpha: 1.000)
        static let primaryOrange: UIColor = UIColor(red: 1.000, green: 0.490, blue: 0.431, alpha: 1.000)
        static let bottomNavigationBGColorUnselected: UIColor = UIColor(red: 0.914, green: 0.933, blue: 0.953, alpha: 1.000)
        static let bottomNavigationBGColorSelected: UIColor = UIColor(red: 0.839, green: 0.863, blue: 0.894, alpha: 1.000)
        static let headerTextLightBG: UIColor = UIColor(red: 0.282, green: 0.286, blue: 0.333, alpha: 1.000)
        static let secondaryButton: UIColor = UIColor(red: 0.945, green: 0.961, blue: 0.973, alpha: 1.000)
        static let secondaryButtonText: UIColor = UIColor(red: 0.447, green: 0.451, blue: 0.490, alpha: 1.000)
        static let white: UIColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        static let subheadColor: UIColor = UIColor(red: 0.604, green: 0.824, blue: 0.969, alpha: 1.000)
        static let numberAndMinutes: UIColor = UIColor(red: 0.302, green: 0.482, blue: 0.647, alpha: 1.000)
        static let bottomNavigationIconUnselected: UIColor = UIColor(red: 0.600, green: 0.612, blue: 0.624, alpha: 1.000)
        static let bottomNavigationIconSelected: UIColor = UIColor(red: 0.361, green: 0.373, blue: 0.380, alpha: 1.000)
    }

    //// Colors

    public class var secondaryOrange: UIColor { return Cache.secondaryOrange }
    public class var primaryOrange: UIColor { return Cache.primaryOrange }
    public class var bottomNavigationBGColorUnselected: UIColor { return Cache.bottomNavigationBGColorUnselected }
    public class var bottomNavigationBGColorSelected: UIColor { return Cache.bottomNavigationBGColorSelected }
    public class var headerTextLightBG: UIColor { return Cache.headerTextLightBG }
    public class var secondaryButton: UIColor { return Cache.secondaryButton }
    public class var secondaryButtonText: UIColor { return Cache.secondaryButtonText }
    public class var white: UIColor { return Cache.white }
    public class var subheadColor: UIColor { return Cache.subheadColor }
    public class var numberAndMinutes: UIColor { return Cache.numberAndMinutes }
    public class var bottomNavigationIconUnselected: UIColor { return Cache.bottomNavigationIconUnselected }
    public class var bottomNavigationIconSelected: UIColor { return Cache.bottomNavigationIconSelected }

}
